[package]
name = "mokita-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.41", features = ["derive"] }
config = "0.15.13"
tokio = { version = "1.46.1", features = ["full"] }
tokio-cron-scheduler = "0.15.1"
